// Code generated by "stringer -type=TCPEvent"; DO NOT EDIT.

package eventsocket

import "strconv"

const _TCPEvent_name = "OpenClose"

var _TCPEvent_index = [...]uint8{0, 4, 9}

func (i TCPEvent) String() string {
	if i < 0 || i >= TCPEvent(len(_TCPEvent_index)-1) {
		return "TCPEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TCPEvent_name[_TCPEvent_index[i]:_TCPEvent_index[i+1]]
}
