# Build example-eventsocket-client.
FROM golang:1.20-alpine3.18 as build
RUN apk --no-cache add git
COPY . /go/src/github.com/m-lab/tcp-info
WORKDIR /go/src/github.com/m-lab/tcp-info
RUN go get -v ./cmd/example-eventsocket-client && \
    go install ./cmd/example-eventsocket-client

# Put it in its own image.
FROM alpine:3.18
COPY --from=build /go/bin/example-eventsocket-client /example-eventsocket-client
WORKDIR /
ENTRYPOINT ["/example-eventsocket-client"]
